### ISSUE TITLE
npm start 错误

### ISSUE THREAD

**Issue by zaphz** [75team/firekylin#103]
$ npm start

> Firekylin@0.12.1 start F:\hz\firekylin
> node www/development.js

[2016-06-01 13:51:54] [THINK] Server running at http://127.0.0.1:8360/
[2016-06-01 13:51:54] [THINK] ThinkJS Version: 2.2.4
[2016-06-01 13:51:54] [THINK] Cluster Status: closed
[2016-06-01 13:51:54] [THINK] WebSocket Status: closed
[2016-06-01 13:51:54] [THINK] File Auto Compile: true
[2016-06-01 13:51:54] [THINK] File Auto Reload: true
[2016-06-01 13:51:54] [THINK] App Enviroment: development

[2016-06-01 13:51:55] [SOCKET] Connect mysql with mysql://:@127.0.0.1:3306/
[2016-06-01 13:51:55] [Error] RangeError: Maximum call stack size exceeded
    at arrayClone (events.js:442:20)
    at emitOne (events.js:93:21)
    at Connection.emit (events.js:182:7)
    at Connection.connection.addCommand (F:\hz\firekylin\node_modules\mysql2\lib\connection.js:83:20)
    at Connection.end (F:\hz\firekylin\node_modules\mysql2\lib\connection.js:620:23)
    at _class.close (F:\hz\firekylin\node_modules\thinkjs\src\adapter\socket\mysql.js:162:23)
    at Connection.<anonymous> (F:\hz\firekylin\node_modules\thinkjs\src\adapter\socket\mysql.js:90:14)
    at emitOne (events.js:95:20)
    at Connection.emit (events.js:182:7)
    at Connection.connection.addCommand (F:\hz\firekylin\node_modules\mysql2\lib\connection.js:83:20)
    at Connection.end (F:\hz\firekylin\node_modules\mysql2\lib\connection.js:620:23)
    at _class.close (F:\hz\firekylin\node_modules\thinkjs\src\adapter\socket\mysql.js:162:23)
    at Connection.<anonymous> (F:\hz\firekylin\node_modules\thinkjs\src\adapter\socket\mysql.js:90:14)
    at emitOne (events.js:95:20)
    at Connection.emit (events.js:182:7)
    at Connection.connection.addCommand (F:\hz\firekylin\node_modules\mysql2\lib\connection.js:83:20)
[2016-06-01 13:51:55] [Error] Error: Connection refused, mysql://:@127.0.0.1:3306/. http://www.thinkjs.org/doc/error_message.html#econnrefused
    at F:\hz\firekylin\node_modules\thinkjs\src\adapter\socket\mysql.js:96:17
    at _class.run (F:\hz\firekylin\node_modules\thinkjs\src\util\await.js:31:30)
    at Object.think.await (F:\hz\firekylin\node_modules\thinkjs\src\core\think.js:855:25)
    at _class._callee$ (F:\hz\firekylin\node_modules\thinkjs\src\adapter\socket\mysql.js:75:18)
    at tryCatch (F:\hz\firekylin\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (F:\hz\firekylin\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (F:\hz\firekylin\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:121:21)
    at step (F:\hz\firekylin\node_modules\thinkjs\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at F:\hz\firekylin\node_modules\thinkjs\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
    at tryCatcher (F:\hz\firekylin\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\hz\firekylin\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\hz\firekylin\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromiseCtx (F:\hz\firekylin\node_modules\bluebird\js\release\promise.js:596:10)
    at Async._drainQueue (F:\hz\firekylin\node_modules\bluebird\js\release\async.js:143:12)
    at Async._drainQueues (F:\hz\firekylin\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (F:\hz\firekylin\node_modules\bluebird\js\release\async.js:17:14)
[2016-06-01 13:51:55] [HTTP] GET /crontab/sync_comment 200 1354ms

**Comment by lizheming** [comment]
你这是不是直接 clone 的仓库安装的....使用的话请使用 http://firekylin.org/release/latest.tar.gz 这个安装版本。
