### ISSUE TITLE
发布文章报错

### ISSUE THREAD

**Issue by pkwenda** [75team/firekylin#162]
一系列操作登录admin账号发布文章点击发送或者保存草稿的时候报错。

npm:2.14.12  node:4.3.1
页面报错：Unexpected token < in JSON at position 0
终端报错信息：
```
[2016-10-18 04:34:47] [Error] Error: EACCES: permission denied, open '/Users/ZhuangXiaoDa/openProject/firekylin/node_modules/.npminstall/uslug/1.0.4/uslug/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:415:20)
    at Module.load (module.js:343:32)
    at Module._load (module.js:300:12)
    at Function.sys_module._load (/Users/ZhuangXiaoDa/openProject/firekylin/node_modules/.npminstall/thinkjs/2.2.13/thinkjs/lib/util/auto_reload.js:195:24)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/ZhuangXiaoDa/openProject/firekylin/node_modules/.npminstall/marked-toc/0.3.0/marked-toc/index.js:14:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module._load (module.js:300:12)
    at Function.sys_module._load (/Users/ZhuangXiaoDa/openProject/firekylin/node_modules/.npminstall/thinkjs/2.2.13/thinkjs/lib/util/auto_reload.js:195:24)
    at Module.require (module.js:353:17)
[2016-10-18 04:34:47] [HTTP] POST /admin/api/post?_r=0.41851926914492177 200 8ms
```

**Comment by pkwenda** [comment]
现在我点击任何一个操作都有此报错信息

**Comment by pkwenda** [comment]
重新安装初始化npm 
这下页面报错：数据库文件（firekylin.sql）不存在，请重新下载
可是明明就在 db下
后台无报错

**Comment by pkwenda** [comment]
我只进行了第一步，当我打算重新安装博客
第二部pm2的时候：
```
localhost:firekylin3 zhuang$ pm2 start pm2.json
[PM2] Applying action restartProcessId on app [firekylin](ids: 0)
[PM2] [firekylin](0) ✓
┌───────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┐
│ App name  │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ watching │
├───────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┤
│ firekylin │ 0  │ fork │ N/A │ errored │ 0       │ 0      │ 0%  │ 0 B    │ disabled │
└───────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by lizheming** [comment]
报 permission denied，是不是你没有权限？

**Comment by pkwenda** [comment]
你这个要对本地磁盘
```
firekylin/node_modules/.npminstall/uslug/1.0.4/uslug/index.js
```
进行IO读写吗？我以为只是操作mysql

**Comment by pkwenda** [comment]
感谢，问题已经解决

**Comment by lizheming** [comment]
读取模块很正常嘛=w= 写倒是不用~
