### ISSUE TITLE
升级为thinkjs2.1之后 babel编译不过

### ISSUE THREAD

**Issue by jtHwong** [75team/firekylin#19]
如题

**Comment by qgy18** [comment]
2.1 升级到 babel6 了，需要做一些修改。具体可以看这里：

https://thinkjs.org/zh-cn/doc/2.1/upgrade.html#toc-cc6

**Comment by jtHwong** [comment]
master分支上 运行gulp还是会出错。 目前暂时使用2.0分支进行学习
版本信息：
node: v5.5.0
npm: 3.6.0
gulp-babel: gulp-babel@6.1.1
错误如下：
```base
[18:57:31] Requiring external module babel-core/register
/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:327
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "es2015" relative to directory "/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin"
    at OptionManager.mergePresets (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:327:17)
    at OptionManager.mergeOptions (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.addConfig (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at compile (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-register/lib/node.js:87:26)
    at loader (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-register/lib/node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jiangtao/Places/Code/Github_Code/development/imjiangtao.com/firekylin/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```
