### ISSUE TITLE
使用VSCODE 调试出现问题 [Error] Error: template not found

### ISSUE THREAD

**Issue by JDDCN** [75team/firekylin#195]
vscode  launch.json 按照thinkjs官网配置，如下：

> { 
 "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "启动程序",
            "program": "${workspaceRoot}\\www\\development.js",
            "cwd": "${workspaceRoot}",
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/app/**"
            ]
        },
        {
            "type": "node",
            "request": "attach",
            "name": "附加到进程",
            "port": 5858
        }
    ]
}

启动，调试控制台输出正常：
>node --debug-brk=20519 --nolazy www\development.js 
Debugger listening on port 20519
[2016-12-14 16:04:29] [THINK] Server running at http://127.0.0.1:8360/
[2016-12-14 16:04:29] [THINK] ThinkJS Version: 2.2.15
[2016-12-14 16:04:29] [THINK] Cluster Status: closed
[2016-12-14 16:04:29] [THINK] WebSocket Status: closed
[2016-12-14 16:04:29] [THINK] File Auto Compile: true
[2016-12-14 16:04:29] [THINK] File Auto Reload: true
[2016-12-14 16:04:29] [THINK] App Enviroment: development
[2016-12-14 16:04:29] [SOCKET] Connect mysql with mysql://root:firekylin@127.0.0.1:3306/mysql
[2016-12-14 16:04:29] [SQL] SHOW COLUMNS FROM `fk_options` 5ms
[2016-12-14 16:04:29] [SQL] SELECT * FROM `fk_options` 3ms
[2016-12-14 16:04:29] [HTTP] GET /crontab/sync_comment 200 799ms

访问 http://127.0.0.1:8360/ 出现问题，调试控制台输出：
>[2016-12-14 16:04:29] [HTTP] GET /crontab/sync_comment 200 799ms
[2016-12-14 16:06:10] [SQL] SHOW COLUMNS FROM `fk_user` 4ms
[2016-12-14 16:06:10] [SQL] SELECT COUNT(id) AS think_count FROM `fk_user` LIMIT 1 1ms
**[2016-12-14 16:06:10] [Error] Error: template not found: **\www\theme\firekylin\index.html**
    at Obj.extend.getTemplate.createTemplate (**\node_modules\nunjucks\src\environment.js:206:31)
    at next (**\node_modules\nunjucks\src\lib.js:210:13)
    at handle (**\node_modules\nunjucks\src\environment.js:252:25)
    at **\node_modules\nunjucks\src\environment.js:263:21
    at next (**\node_modules\nunjucks\src\lib.js:207:13)
    at Object.exports.asyncIter (**\node_modules\nunjucks\src\lib.js:214:5)
    at Obj.extend.getTemplate (**\node_modules\nunjucks\src\environment.js:242:17)
    at Obj.extend.render (**\node_modules\nunjucks\src\environment.js:304:14)
    at module.exports.render (**\node_modules\nunjucks\index.js:72:14)
    at promisify (**\node_modules\thinkit\lib\index.js:47:10)
    at Promise.module.exports.Promise._execute (**\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise.module.exports.Promise._resolveFromExecutor (**\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (**\node_modules\bluebird\js\release\promise.js:77:14)
    at promisify (**\node_modules\thinkit\lib\index.js:46:12)
    at _class._callee$ (**\node_modules\thinkjs\lib\adapter\template\nunjucks.js:91:48)
    at tryCatch (**\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:88:40)
[2016-12-14 16:06:10] [HTTP] GET / 200 283ms

网页返回500 错误页面：
>Internal Server Error
template not found: D:\own\code\github\firekylin\www\theme\firekylin\index.html

另，在项目目录下，执行npm start ，正常，输出如下：
>$ npm start
Firekylin@0.13.1 start D:\own\code\github\firekylin
node www/development.js
[2016-12-14 16:13:10] [THINK] Server running at http://127.0.0.1:8360/
[2016-12-14 16:13:10] [THINK] ThinkJS Version: 2.2.15
[2016-12-14 16:13:10] [THINK] Cluster Status: closed
[2016-12-14 16:13:10] [THINK] WebSocket Status: closed
[2016-12-14 16:13:10] [THINK] File Auto Compile: true
[2016-12-14 16:13:10] [THINK] File Auto Reload: true
[2016-12-14 16:13:10] [THINK] App Enviroment: development
[2016-12-14 16:13:10] [SOCKET] Connect mysql with mysql://root:firekylin@127.0.0.1:3306/mysql
[2016-12-14 16:13:10] [SQL] SHOW COLUMNS FROM `fk_options` 7ms
[2016-12-14 16:13:10] [SQL] SELECT * FROM `fk_options` 3ms
[2016-12-14 16:13:10] [HTTP] GET /crontab/sync_comment 200 581ms
[2016-12-14 16:13:17] [SQL] SHOW COLUMNS FROM `fk_user` 4ms
[2016-12-14 16:13:17] [SQL] SELECT COUNT(id) AS think_count FROM `fk_user` LIMIT 1 1ms
[2016-12-14 16:13:17] [HTTP] GET / 200 268ms

对比来看是vscode调试引入的问题，希望可以指点一下，谢谢~

**Comment by lizheming** [comment]
报错的原因是模板引擎没有找到模板，是不是相对目录设置的有问题？

**Comment by JDDCN** [comment]
@lizheming 目录设置？除了vscode的 launch.json 外，没有进行其他特别的设置。 根目录下执行npm start是没有问题的~
package.json 中有效启动配置如下：
>{
  "name": "Firekylin",
  "description": "A Simple & Fast Node Bloging Platform Base On ThinkJS 2.0 & ReactJS & ES2015+",
  "version": "0.13.1",
  "scripts": {
    **"start": "node www/development.js",**
    "compile": "babel --presets es2015-loose,stage-1 --plugins transform-runtime src/ --out-dir app/",
    "watch-compile": "node -e \"console.log('<npm run watch-compile> no longer need, use <npm start> command direct.');console.log();\"",
    "watch": "npm run watch-compile",
    "copy-package": "node copy_package.js",
    "webpack": "webpack --watch",
    "webpack.build": "webpack",
    "webpack.build.production": "webpack --config=webpack.production.config.babel.js"
  }

从配置来看两个执行入口，最后都是去执行 www\development.js 了，npm start 正常，vscode出错。
如果是目录设置的问题，可以告知一下从哪里下手查一下吗？没有头绪呀~~

**Comment by lizheming** [comment]
那你看看 `D:\own\code\github\firekylin\www\theme\firekylin\index.html` 这个文件有没有？

**Comment by JDDCN** [comment]
@lizheming 这个必然是有的~ 问题出现的第一时间就查看了。

**Comment by lizheming** [comment]
那就不是很清楚了，我今天按照你的配置试了下在我这是可以的。

**Comment by JDDCN** [comment]
@lizheming 额~~ 你那边vscode 调试控制台输出是什么？方便的话，贴一下，我对比看看。

**Comment by lizheming** [comment]
![image](https://cloud.githubusercontent.com/assets/424491/21263463/e2f4e72c-c3d1-11e6-9bd0-09d3c1e9c10c.png)

**Comment by lizheming** [comment]
Closing due to lack of activity.
