### ISSUE TITLE
/admin 报错 TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Jerret321** [75team/firekylin#235]
只有production才有此问题~
```bash
[Error] TypeError: Cannot read property 'forEach' of undefined
    at _class._callee$ (/var/www/blog/app/home/controller/post.js:101:24)
    at tryCatch (/var/www/blog/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/www/blog/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/www/blog/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/var/www/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /var/www/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at propagateAslWrapper (/root/.nvm/versions/node/v6.9.1/lib/node_modules/pm2/node_modules/async-listener/index.js:421:23)
    at /root/.nvm/versions/node/v6.9.1/lib/node_modules/pm2/node_modules/async-listener/index.js:458:70
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
```

**Comment by lizheming** [comment]
我这查了下没有复现这个问题，我看了下可能是数据问题，你可以追踪下代码看看。
`list.data.forEach` undefined 的话只能说明 `list.data` 不是数组，但是 `countSelect` 返回的数据按照[源码](https://github.com/thinkjs/thinkjs/blob/master/src/model/base.js#L523) 显示肯定是一个数组的。

**Comment by Jerret321** [comment]
恩 我回头找找修一下 issue先记录

**Comment by lizheming** [comment]
OK, thx any way~

**Comment by Jerret321** [comment]
不影响功能

**Comment by lizheming** [comment]
是什么原因呢？

**Comment by Jerret321** [comment]
数据库升级 不干净

**Comment by lizheming** [comment]
OK
