### ISSUE TITLE
升级到0.15.3后，直接从主分支上拉取的代码运行不了。

### ISSUE THREAD

**Issue by westpsk** [75team/firekylin#245]
都配置完成之后，启动项目后报一个404的错。
theme:20 GET http://westpsk.com/static/js/admin.js  <- 提示这个找不到

怀疑编译失败，所以手动npm run compile  果然报错了如下：

```
Error: Couldn't find preset "es2015-loose" relative to directory "src/admin/config"
    at /home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/ivan/blogv2/firekylin/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/home/ivan/blogv2/firekylin/node_modules/babel-cli/lib/babel/util.js:50:22)
```

查了一下，单独安装了 babel-preset-es2015-loose 成功，通过npm start可以成功启动。

但是进入后台后 http://westpsk.com/admin/appearance/theme 有出问题了：

![image](https://cloud.githubusercontent.com/assets/12495017/23596026/b49e6226-0261-11e7-8a43-9796d53f8a33.png)

**Comment by lizheming** [comment]
你重新拉下代码然后重新 npm install 一下吧。`npm run compile` 这个 `es2015-loose` 应该要修改成 `es2015` 了，我一直忘记修来着。你的 npm 还是 2.x 么？这个应该是 `codemirror` 这个模块找不到了，`react-codemirror` 有依赖 `codemirror` 如果是 3.x 打平的依赖的话就没问题了，只有 2.x 会提示找不到，已经在 Firekylin 中增加 `codemirror` 的依赖。

**Comment by westpsk** [comment]
我的node版本是v7.7.1
npm版本是4.4.0

看了node_modules目录下也安装了react-codemirror(v0.3.0)和codemirror(v5.24.2)两个包 ... 

奇怪 这样引却识别不到。。 

```
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/monokai.css'; 
```

**Comment by lizheming** [comment]
那你检查下你安装的 codemirror 库里面是否有这两个样式文件？

**Comment by westpsk** [comment]
有的，我之前用react引codemirror样式文件时也遇到过一样的问题。。我当时把node_modules里面的的css文件直接拿出来放到了外面。。。

**Comment by lizheming** [comment]
你的全局 webpack 版本是多少？
