### ISSUE TITLE
关于Ghost和Wordpress导入的两个问题

### ISSUE THREAD

**Issue by choicky** [75team/firekylin#248]
@lizheming 
请教两个问题。

1、Ghost 的导入
我的Ghost导出的.json大概有1.4M。我在 Firekylin 的后台导入时，一直停留在“上传中”的界面。服务器是国内的，平时上传都是挺快的，暂时不明白停留在“上传中”的原因是什么。

2、能不能把Ghost、Wordpress 的数据导入同一个 Firekylin 中？
我之前分别用 Ghost Wordpress 写了博客，现在想把它俩的数据合并，直接导入是会覆盖的吧？

firekylin 是 0.15.3
如你方便，我可以把我的ghost数据发到你email

**Comment by lizheming** [comment]
1. @excaliburhan 麻烦你跟进下这个 issue 吧
2. 可以，不会覆盖

**Comment by choicky** [comment]
@excaliburhan 如有需要，可留个gmail，我把我的ghost数据发过去。
@lizheming Thanks

**Comment by excaliburhan** [comment]
@choicky 不要意思周末没法用电脑。我的gmail: edwardhjp@gmail.com，方便的话，把你的ghost导出的json给我看下。

**Comment by choicky** [comment]
@excaliburhan 已发到你gmail了，thanks

**Comment by excaliburhan** [comment]
@lizheming 问题应该是后面某次更新的时候添加了分类字段，当firekylin中没有分类的时候，得到的分类列表是undefined，需要对其做下兼容处理。

**Comment by excaliburhan** [comment]
@choicky 我没有碰到一直上传中的提示，推测应该是网络问题，等下次修复你再看下吧

**Comment by choicky** [comment]
@excaliburhan @lizheming 多谢两位。

另，我觉得theme是影响很多用户决定的因素，迫切希望大神们多开发几套漂亮的皮肤啊。

我能力有限，帮不上忙。。。。

**Comment by choicky** [comment]
多谢 0.15.4 版。但是，我导入 wordpress 和 ghost 依然存在问题……

导入 Ghost 的数据时，web提示 `共导入文章 156 篇，页面 1 页，分类 0 个，标签 189 个`，但刷新或重启 firekylin，就发现依然没有新导入的数据。 `pm2 stop`了firekylin之后，用`npm start`的话，就发现终端输出了很多行`[TypeError: retTag.includes is not a function]`

导入wordpress的数据时，web直接提示`IMPORT_FAIL`，`npm start`发现终端输出`[TypeError: Cannot read property '0' of undefined]`

**Comment by excaliburhan** [comment]
@choicky `[TypeError: retTag.includes is not a function]`应该是node版本过低的原因，你用的是4.x的版本吧？如果是4.x的版本，可以用`node --harmony www/production.js`启动试试看，或者升级到6.x/7.x的版本。

**Comment by lizheming** [comment]
@excaliburhan 目前版本要求是 `node >= 4.0`，暂时还是先改下写法或者加一下 polyfill 吧。等 thinkjs 3.x 出来最低版本 6.0 就不用管这么多了，嘿嘿~

**Comment by choicky** [comment]
@excaliburhan @lizheming 
更新node到6.x之后，Ghost导入OK了。但WordPress导入依然不行，提示：
```
TypeError: Cannot read property '0' of undefined
    at /data/choicky/www/zhoucaiqi.com/app/admin/service/import/wordpress.js:407:45
    at Array.map (native)
    at _class._callee6$ (/data/choicky/www/zhoucaiqi.com/app/admin/service/import/wordpress.js:405:36)
    at tryCatch (/data/choicky/www/zhoucaiqi.com/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/data/choicky/www/zhoucaiqi.com/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/data/choicky/www/zhoucaiqi.com/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/data/choicky/www/zhoucaiqi.com/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /data/choicky/www/zhoucaiqi.com/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/data/choicky/www/zhoucaiqi.com/node_modules/core-js/library/modules/_export.js:35:28)
    at _class.<anonymous> (/data/choicky/www/zhoucaiqi.com/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at _class.tag (/data/choicky/www/zhoucaiqi.com/app/admin/service/import/wordpress.js:426:22)
    at _class._callee7$ (/data/choicky/www/zhoucaiqi.com/app/admin/service/import/base.js:259:29)
    at tryCatch (/data/choicky/www/zhoucaiqi.com/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/data/choicky/www/zhoucaiqi.com/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/data/choicky/www/zhoucaiqi.com/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/data/choicky/www/zhoucaiqi.com/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

**Comment by lizheming** [comment]
。。你这人真够可以的。。。突然来一句 wordpress 导入依然不行。。。你从 issue 报开始就没说 wordpress 导入有问题啊。。。。服了。。。

把你的 wp 导出数据发我吧 i#imnerd.org

**Comment by choicky** [comment]
@lizheming 邮件已发，Thanks

主贴是没提到WordPress，只是后来回帖提了一下，所以说了一句“ wordpress 导入依然不行”.... 

多谢各位的努力。

**Comment by excaliburhan** [comment]
@lizheming 我看了app.jsx是有babel polyfill的，理论上应该是有includes方法的呀。我觉得用firekylin的人肯定是喜欢async/await的，没理由用4.x的node啊。逃)

**Comment by choicky** [comment]
我之前用的是 Ghost
Ghost这货之前支持0.x 的node吧，印象中，目前也就支持4.x的
