### ISSUE TITLE
支持 HTTP/2

### ISSUE THREAD

**Issue by welefen** [75team/firekylin#31]
增加支持 HTTP/2 的安装脚本

**Comment by songguangyu** [comment]
已增加 HTTP/2 自动安装脚本 项目根目录下 运行 sh https.sh example.com www.example.com 来自动部署https，小伙伴们可以反馈一下问题，进行完善

**Comment by qgy18** [comment]
貌似 CentOS 的 `openssl.cnf` 默认在这里：
```
/usr/local/openssl/ssl/openssl.cnf
```

**Comment by songguangyu** [comment]
在自动化脚本里 我们也考虑到了 这一点 并不是所有得机器都是Linux 。/etc/ssl/openssl.cnf 路径不存在的话 会让用户手动输入openssl.cnf的路径

**Comment by BeAce** [comment]
我在项目根目录下运行 
`sh https.sh beacelee.com www.beacelee.com`
后，成功了。但是，再次启动服务nginx是，报这样的错：
`nginx: [emerg] BIO_new_file("/etc/nginx/%path/ssl/chained.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/%path/ssl/chained.pem','r')`

是因为我事先没有安装证书吗，之前在apache的环境下，后来切换到nginx，试问证书需要重装吗？

**Comment by lizheming** [comment]
@BeAce 你这可能是 nginx.conf 文件中证书文件地址替换失败了，你先手动修改一下看看是否能够成功。

**Comment by jiespring** [comment]
希望吧设置https的方法写进安装教程！

**Comment by jiespring** [comment]
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/root/wwj/firekylin/ssl/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by jiespring** [comment]
`nginx: [emerg] SSL_CTX_use_PrivateKey_file("/root/wwj/firekylin/ssl/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: configuration file /etc/nginx/nginx.conf test failed
`

**Comment by jiespring** [comment]
执行了https.sh脚本，然后修改了nginx.conf配置文件，再nginx -t查错，最后出现这个。

**Comment by jiespring** [comment]
ssl证书：
方法A：
第一步https://github.com/xdtianyu/scripts/tree/master/lets-encrypt
第二步openssl dhparam -out /etc/ssl/certs/dhparams.pem 2048
第三步，修改博客根目录下的nginx.conf，注意路径需要改成1、2步生成的文件路径。
nginx重启不了的话，我重新安装nginx才弄好。
方法B：当然，我想用你们脚本的方法也可能成功，但是我nginx -t调好后，之前的restart出错情况还在。
最后才想到吧nginx重新安装。现在全弄好了。

**Comment by jiespring** [comment]
我是用方法A生成了三个文件fullchain.pem( Nginx所需要ssl_certificate文件)privkey.pem(Nginx所需ssl_certificate_key)，
       第2步是生成ssl_dhparam，
       在博客根目录下修改nginx.conf，把第一段的server前加#，把https server下一行server开始全部#删掉，把3个文件的路径改成自己的路径，完成后，nginx -t检查错误，错误排查完后，我的nginx restart出现了错误，我就把niginx卸载重装，现在restart没问题了，
      再pm2加载pm2.json，打开网站，https可以了。

**Comment by golmic** [comment]
请问运行 sh https.sh example.com www.example.com 后再怎么操作呢，把 nginx_default.conf 里面的内容修改成nginx的配置后，报错，没有ssl目录

**Comment by jiespring** [comment]
你看看nginx配置文件里关于ssl证书的路径。

**Comment by golmic** [comment]
@jiespring 我是说我的网站目录下没有ssh文件夹

**Comment by jiespring** [comment]
@golmic 你新建一个试试呗，我也不记得自己是否遇到过你这种情况，不行就换个方法。

**Comment by golmic** [comment]
这可能不是这个项目的issue，不过我用Google没查到解决方案。
运行sh https.sh domain.com 后报错如下：
> 检测 openssl 成功
> 检测 python 成功
> Parsing account key...
> Parsing CSR...
> Registering account...
> Already registered!
> Signing certificate...
> Traceback (most recent call last):
>   File "acme_tiny.py", line 198, in <module>
>     main(sys.argv[1:])
>   File "acme_tiny.py", line 194, in main
>     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
>   File "acme_tiny.py", line 161, in get_crt
>     raise ValueError("Error signing certificate: {0} {1}".format(code, result))
> ValueError: Error signing certificate: 400 {
>   "type": "urn:acme:error:malformed",
>   "detail": "Error creating new cert :: at least one DNS name is required",
>   "status": 400
> }

**Comment by opsarno** [comment]
这个是 nginx端做支持，跟博客系统没有关系吧。
