### ISSUE TITLE
目前版本里面post_tag和tag的表结构不完善

### ISSUE THREAD

**Issue by jtHwong** [75team/firekylin#6]
如题，可以把表结构补充到firekylin.sql里面么

**Comment by ejzhang** [comment]
CREATE TABLE `fk_tag` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `fk_tag` (`id`, `name`) VALUES (1, 'QUC'), (2, 'JS'), (3, 'SDK'), (4, '文档'), (5, 'Markdown'), (6, '简明指南'), (7, '业务标识'), (8, '命名规范'), (9, '快速上手'), (10, '手机号'), (11, '用户邮箱'), (12, '登录状态'), (13, '用户信息'), (14, '密保信息'), (15, '初始化');

CREATE TABLE `fk_post_tag` (
  `post_id` int(10) unsigned NOT NULL,
  `tag_id` int(10) unsigned NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `fk_post_tag` (`post_id`, `tag_id`) VALUES (165, 1), (165, 2), (165, 3), (165, 4), (166, 5), (166, 6), (167, 7), (167, 8), (168, 9), (169, 10), (171, 11), (172, 12), (173, 13), (174, 14), (175, 15);

**Comment by ejzhang** [comment]
难道是我打开方式不对？
```[2015-11-26 19:28:32] [SQL] SELECT `post_id`,`tag_id`,`name` FROM `fk_post_tag` INNER JOIN `fk_tag` ON fk_post_tag.`tag_id`=fk_tag.`id` WHERE ( `post_id` IN (178,177,175,174,173,172,171,170,169,168) ) 2ms
[2015-11-26 19:28:32] [Error] TypeError: C:\firekylin\view\web\post_list.html:4
    2|
    3| <% var index = true; %>
 >> 4| <div itemscope itemtype="http://schema.org/Blog">
    5|   <% list.forEach(function(post) { %>
    6|   <article class="post" itemprop="blogPost" itemscope itemtype="http://schema.org/BlogPosting"><% include inc/article.html %></article>
    7|   <% }) %>

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (C:\firekylin\node_modules\ejs\lib\ejs.js:464:12), <anonymous>:246:20)
    at eval (eval at <anonymous> (C:\firekylin\node_modules\ejs\lib\ejs.js:464:12), <anonymous>:272:9)
    at eval (eval at <anonymous> (C:\firekylin\node_modules\ejs\lib\ejs.js:464:12), <anonymous>:370:9)
    at Array.forEach (native)
    at eval (eval at <anonymous> (C:\firekylin\node_modules\ejs\lib\ejs.js:464:12), <anonymous>:195:13)
    at returnedFn (C:\firekylin\node_modules\ejs\lib\ejs.js:493:17)
    at _default.run$ (C:\firekylin\node_modules\thinkjs\lib\adapter\template\ejs.js:60:76)
    at tryCatch (C:\firekylin\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\firekylin\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\firekylin\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:
100:21)```

**Comment by jtHwong** [comment]
@ejzhang 看报错的信息 你这是少了个name

**Comment by blackMao** [comment]
已经更新~
