### ISSUE TITLE
Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'

### ISSUE THREAD

**Issue by 721687** [75team/firekylin#70]
本地安装  和 线上安装都是报这个错误

本地环境：
node 4.4

Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'

[2016-04-06 22:59:30] [Error] Error: ER_BAD_FIELD_ERROR: Champ 'undefined' inconnu dans where clause
    at Query.Sequence._packetToError (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\protocol\sequences\Query.js:83:18)
    at Protocol._parsePacket (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\protocol\Protocol.js:274:23)
    at Parser.write (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:529:20)
    --------------------
    at Protocol._enqueue (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\protocol\Protocol.js:135:48)
    at Connection.query (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\mysql\2.9.0\mysql\lib\Connection.js:201:25)
    at F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\thinkit\4.8.0\thinkit\lib\index.js:47:10
    at Promise._execute (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\bluebird\3.1.1\bluebird\js\release\debuggability.js:180:9)
    at Promise._resolveFromExecutor (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\bluebird\3.1.1\bluebird\js\release\promise.js:460:18)
    at new Promise (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\bluebird\3.1.1\bluebird\js\release\promise.js:76:14)
    at F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\thinkit\4.8.0\thinkit\lib\index.js:46:12
    at _class._callee2$ (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\thinkjs\2.2.1\thinkjs\lib\adapter\socket\mysql.js:205:25)
    at tryCatch (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\babel-runtime\6.3.19\babel-runtime\regenerator\runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\babel-runtime\6.3.19\babel-runtime\regenerator\runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\babel-runtime\6.3.19\babel-runtime\regenerator\runtime.js:121:21)
    at step (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\babel-runtime\6.3.19\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\babel-runtime\6.3.19\babel-runtime\helpers\asyncToGenerator.js:28:13
    at tryCatcher (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\bluebird\3.1.1\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\bluebird\3.1.1\bluebird\js\release\promise.js:489:31)
    at Promise._settlePromise (F:\node\iloved\appidz3bgkdv8uv\node_modules\.npminstall\bluebird\3.1.1\bluebird\js\release\promise.js:546:18)

**Comment by lizheming** [comment]
用的是哪个版本？是 0.5 最新的安装包么？

**Comment by 721687** [comment]
之前使用的是0.4版本，刚更新到0.5已经没问题了！谢谢！

**Comment by KaronAmI** [comment]
弱弱地问下，什么0.5？我也遇到这个问题！请问怎么解决好

**Comment by lizheming** [comment]
@KaronAmI 是安装的时候报的么？

**Comment by lizheming** [comment]
@KaronAmI 安装的报错是正常的，是要删除老数据库老数据库不存在的报错，所以有报错，这个报错不影响后续的使用。

**Comment by KaronAmI** [comment]
原来是这样，谢谢解答
